export const FETCH_ROBOTS_REQUEST = 'FETCH_ROBOTS_REQUEST';
export const FETCH_ROBOTS_SUCCESS = 'FETCH_ROBOTS_SUCCESS';
export const FETCH_ROBOTS_FAILURE = 'FETCH_ROBOTS_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const FILTER_ROBOTS = 'FILTER_ROBOTS';
